### PR TITLE
160 new phrases! :D

### PR DESCRIPTION
**Pull request by AZGamezYT**

### CODE REVIEW

**Comment by AZGamezYT** [comment]
this was meant to be part of phrases, not deaths (sorry)

**Comment by Geming400** [comment]
Can't you just fix it manually

**Comment by NicknameGG** [comment]
Oh yeah can you fix them to the phrases file so i can merge the request

**Comment by AZGamezYT** [comment]
Alright let's go

**Comment by NicknameGG** [comment]
Closing cuz of #16

**Pull request closed without merging**
